#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

echo 'Sourcing boxen'
SHELL='/bin/zsh'
source /opt/boxen/env.sh

PATH="/opt/boxen/homebrew/Cellar/coreutils/8.23_1/libexec/gnubin:$PATH"
MANPATH="/opt/boxen/homebrew/Cellar/coreutils/8.23_1/libexec/gnuman:$MANPATH"


ZSH_HOME='/Users/indika/.zprezto'
# ZSH_HOME=$HOME/.zprezto
source /Users/indika/.zprezto/architectures/osx-cobalt.sh

alias resource="source ~/.zshrc"
