#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

ZSH_HOME='/home/deploy/.zprezto'

source /home/deploy/.rbenvrc
source /home/deploy/.zprezto/architectures/linux-shan.sh

alias resource="source ~/.zshrc"
